spring.application.name=09_One-Many_Mapping_Project-1
spring.datasource.url = jdbc:mysql://localhost:3306/one_many_mapping
spring.datasource.username = Spring
spring.datasource.password = Rshivansh@094
spring.jpa.hibernate.ddl-auto=create
spring.jackson.serialization.fail-on-empty-beans=false

# Added Properties
server.port=8080

springdoc.swagger-ui.path=/swagger-ui.html

#JWT

app.jwt.secret=ThisIsASecretKeyForJWTAuthenticationInSpringBootManyToManyProject12345
app.jwt.expiration-ms=4000000